### ISSUE TITLE
0 should be allowed for the number of VMs

### ISSUE THREAD

**Issue by briandoconnor** [CloudBindle/youxia#16]
When you currently specify "--total-nodes-num 0" the code throws errors and ends up passing -1 around.  The reason I'd like to be able to specify 0 here is I'd like to keep Youxia running but, occasionally, tear down all instances.  This could be useful for a variety of reasons... wanting to pause processing without manually terminating a bunch of nodes, wanting to "clean out" a fleet of hosts when a new AMI is available, etc.

**Comment by denis-yuen** [comment]
Hi,
I think the messages you saw are just informational. They aren't actually errors. The program just stops properly when it seems that you want to deploy a negative number of clients. 

ex:

    $ java -jar youxia-deployer/target/youxia-deployer-*-jar-with-dependencies.jar --ansible-playbook ansible_sensu/site.yml --max-spot-price 0 --batch-size 5 --total-nodes-num 0
    11:11:06.511 [main] INFO  i.c.youxia.listing.AwsListing - Located 17 relevant instances on AWS
    11:11:06.512 [main] INFO  i.c.youxia.deployer.Deployer - Found 17 clients
    11:11:06.513 [main] INFO  i.c.youxia.deployer.Deployer - Need -17 more clients
    11:11:06.513 [main] INFO  i.c.youxia.deployer.Deployer - After batch limit, we can requisition up to -17 this run
    $ echo $?
    0
