### ISSUE TITLE
Runtime statistics gathering i.e. feature to make lincoln happy

### ISSUE THREAD

**Issue by briandoconnor** [CloudBindle/youxia#17]
It would be great to have Youxia dump some cost stats each time it runs, so we can have a simple way to present a burn rate on pancancer.info.  Lincoln and Vincent ask me regularly for a report on our PanCancer expenses.  Would be fun to have a "Youxia saved you $X" report where it compares the runtime costs based on spot pricing vs what you would have spent.

Again, start simple but this would be a great feature to underscore why you built Youxia.

**Comment by denis-yuen** [comment]
We managed to do this with detailed amazon billing, will need a script to process those records.
