### ISSUE TITLE
Option to Not Reap Failed Nodes

### ISSUE THREAD

**Issue by briandoconnor** [CloudBindle/youxia#27]
Option for the reaper to only reap nodes with successful workflows and keep the failed VMs around.  Idea here is this is useful in debugging a workflow.  If most are successful then they are reaped and resources cleaned up.  For the few that fail the VMs are kept around for a person to investigate.

**Comment by denis-yuen** [comment]
This is obsolete. In arch3, we keep track of failure states independently and use kill lists to kill only successful workflows. 
With the advent of Whitestar, the reaper is no longer able to determine failure state actually since there is no web service anymore.
